#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import wiry


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode wiry'
    )

    parser.add_argument(
        "input_text",
        help='The text to make wiry'
    )

    args = vars(parser.parse_args())

    print(wiry(**args))


if __name__ == '__main__':
    main()
