#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import script


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode script'
    )

    parser.add_argument(
        "input_text",
        help='The text to make script'
    )

    args = vars(parser.parse_args())

    print(script(**args))


if __name__ == '__main__':
    main()
