#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import typewriter


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode typewriter'
    )

    parser.add_argument(
        "input_text",
        help='The text to make typewriter'
    )

    args = vars(parser.parse_args())

    print(typewriter(**args))


if __name__ == '__main__':
    main()
