#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import magic


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode magic'
    )

    parser.add_argument(
        "input_text",
        help='The text to make magic'
    )

    args = vars(parser.parse_args())

    print(magic(**args))


if __name__ == '__main__':
    main()
