#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import bolditalics


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode bolditalics'
    )

    parser.add_argument(
        "input_text",
        help='The text to make bolditalics'
    )

    args = vars(parser.parse_args())

    print(bolditalics(**args))


if __name__ == '__main__':
    main()
