#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import reverse


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode reverse'
    )

    parser.add_argument(
        "input_text",
        help='The text to make reverse'
    )

    args = vars(parser.parse_args())

    print(reverse(**args))


if __name__ == '__main__':
    main()
