#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import strange


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode strange'
    )

    parser.add_argument(
        "input_text",
        help='The text to make strange'
    )

    args = vars(parser.parse_args())

    print(strange(**args))


if __name__ == '__main__':
    main()
