#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import apothecary


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode apothecary'
    )

    parser.add_argument(
        "input_text",
        help='The text to make apothecary'
    )

    args = vars(parser.parse_args())

    print(apothecary(**args))


if __name__ == '__main__':
    main()
