#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import serif


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode serif'
    )

    parser.add_argument(
        "input_text",
        help='The text to make serif'
    )

    args = vars(parser.parse_args())

    print(serif(**args))


if __name__ == '__main__':
    main()
