#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import italics


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode italics'
    )

    parser.add_argument(
        "input_text",
        help='The text to make italics'
    )

    args = vars(parser.parse_args())

    print(italics(**args))


if __name__ == '__main__':
    main()
