#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import heavyCircled


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode heavy circled'
    )

    parser.add_argument(
        "input_text",
        help='The text to convert'
    )

    args = vars(parser.parse_args())

    print(heavyCircled(**args))


if __name__ == '__main__':
    main()
