#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import parenthesized


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode parenthesized'
    )

    parser.add_argument(
        "input_text",
        help='The text to make parenthesized'
    )

    args = vars(parser.parse_args())

    print(parenthesized(**args))


if __name__ == '__main__':
    main()
