#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import magic2


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode magic2'
    )

    parser.add_argument(
        "input_text",
        help='The text to make magic2'
    )

    args = vars(parser.parse_args())

    print(magic2(**args))


if __name__ == '__main__':
    main()
