#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import smallcaps


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode smallcaps'
    )

    parser.add_argument(
        "input_text",
        help='The text to make smallcaps'
    )

    args = vars(parser.parse_args())

    print(smallcaps(**args))


if __name__ == '__main__':
    main()
