#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import blue


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode blue'
    )

    parser.add_argument(
        "input_text",
        help='The text to make blue'
    )

    args = vars(parser.parse_args())

    print(blue(**args))


if __name__ == '__main__':
    main()
