#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import monospaced


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode monospaced'
    )

    parser.add_argument(
        "input_text",
        help='The text to make monospaced'
    )

    args = vars(parser.parse_args())

    print(monospaced(**args))


if __name__ == '__main__':
    main()
