#! /usr/bin/env python3

# Standard library
import argparse

# Local
from fancify_text import boxed


def main():
    parser = argparse.ArgumentParser(
        description='Convert text to unicode boxed'
    )

    parser.add_argument(
        "input_text",
        help='The text to make boxed'
    )

    args = vars(parser.parse_args())

    print(boxed(**args))


if __name__ == '__main__':
    main()
